export type Transaction = { id: string; title: string; category: string; amount: number; type: 'income' | 'expense'; date: string; method: string };
export type Preferences = { theme: string; accent: string; font: string; mode: string; card: string; button: string; radius: number; density: string; currency: string; dateFormat: string; frequency: string; notifications: Record<string, boolean> };
export type ChatMessage = { id: string; role: 'user' | 'assistant'; parts: { type: 'text'; text: string }[] };
export type Thread = { id: string; title: string; updatedAt: number; messages: ChatMessage[] };
export const categories = ['Food', 'Transport', 'Shopping', 'Utilities', 'Entertainment', 'Education', 'Health', 'Other'];
export function monthlySeries(items: Transaction[]) { const now=new Date(); return Array.from({length:6},(_,index)=>{const date=new Date(now.getFullYear(),now.getMonth()-5+index,1);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;const {income,expense}=totals(items.filter(item=>item.date.startsWith(key)));return {month:date.toLocaleString('en',{month:'short'}),income,expense,savings:income-expense};}); }
export const defaultPreferences: Preferences = { theme:'Midnight AI',accent:'#4d85ff',font:'Inter',mode:'Light',card:'Glass',button:'Rounded',radius:16,density:'Comfortable',currency:'INR',dateFormat:'DD/MM/YYYY',frequency:'Daily',notifications: Object.fromEntries(['Budget Alerts','Upcoming Payment Alerts','Savings Reminders','Goal Milestones','AI Recommendations','Spending Alerts'].map(x=>[x,true])) };
export function money(amount: number, currency = 'INR') { return new Intl.NumberFormat(currency === 'INR' ? 'en-IN' : 'en-US',{style:'currency',currency,maximumFractionDigits:0}).format(amount * ({INR:1,USD:0.012,EUR:0.011,GBP:0.009}[currency as 'INR'] ?? 1)); }
export const totals = (items: Transaction[]) => ({ income: items.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0), expense:items.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0) });
export function formatDate(date: string, format: string) { const [y,m,d]=date.split('-'); return format==='YYYY-MM-DD' ? date : format==='MM/DD/YYYY' ? `${m}/${d}/${y}` : `${d}/${m}/${y}`; }
