export type Transaction = { id: string; title: string; category: string; amount: number; type: 'income' | 'expense'; date: string; method: string };
export type Preferences = { theme: string; accent: string; font: string; mode: string; card: string; button: string; radius: number; density: string; currency: string; dateFormat: string; frequency: string; notifications: Record<string, boolean> };
export type ChatMessage = { id: string; role: 'user' | 'assistant'; parts: { type: 'text'; text: string }[] };
export type Thread = { id: string; title: string; updatedAt: number; messages: ChatMessage[] };
export const categories = ['Food', 'Transport', 'Shopping', 'Utilities', 'Entertainment', 'Education', 'Health', 'Other'];
export const seedTransactions: Transaction[] = [
  ['Salary','Income',42000,'income','2026-09-01','Bank transfer'],['Freelance Project','Income',6000,'income','2026-09-04','UPI'],['Swiggy','Food',1260,'expense','2026-09-27','UPI'],['Zomato','Food',890,'expense','2026-09-25','UPI'],['Uber','Transport',640,'expense','2026-09-24','UPI'],['Petrol','Transport',1800,'expense','2026-09-22','Debit card'],['Amazon','Shopping',2450,'expense','2026-09-20','Credit card'],['Electricity Bill','Utilities',1540,'expense','2026-09-18','UPI'],['Netflix','Entertainment',649,'expense','2026-09-16','Debit card'],['Gym Membership','Health',1200,'expense','2026-09-14','UPI'],['Coffee','Food',420,'expense','2026-09-13','UPI'],['Clothing','Shopping',2190,'expense','2026-09-11','Debit card'],['Mobile Recharge','Utilities',799,'expense','2026-09-09','UPI'],['College Expense','Education',2800,'expense','2026-09-07','Bank transfer'],['Groceries','Food',3200,'expense','2026-09-06','UPI'],['Movie Night','Entertainment',750,'expense','2026-09-05','UPI'],['Metro Card','Transport',900,'expense','2026-09-03','UPI'],['Pharmacy','Health',580,'expense','2026-09-02','UPI']
].map(([title,category,amount,type,date,method], i) => ({id: `seed-${i}`,title: String(title),category: String(category),amount: Number(amount),type: type as Transaction['type'],date: String(date),method: String(method)}));
export const monthly = [
  { month:'Apr', income:42000, expense:28600, savings:13400 },{ month:'May', income:45000, expense:31400, savings:13600 },{ month:'Jun', income:43000, expense:27200, savings:15800 },{ month:'Jul', income:46500, expense:33200, savings:13300 },{ month:'Aug', income:44000, expense:29600, savings:14400 },{ month:'Sep', income:48000, expense:22068, savings:25932 }
];
export const defaultPreferences: Preferences = { theme:'Midnight AI',accent:'#4d85ff',font:'Inter',mode:'Dark',card:'Solid',button:'Rounded',radius:16,density:'Comfortable',currency:'INR',dateFormat:'DD/MM/YYYY',frequency:'Daily',notifications: Object.fromEntries(['Budget Alerts','Upcoming Payment Alerts','Savings Reminders','Goal Milestones','AI Recommendations','Spending Alerts'].map(x=>[x,true])) };
export function money(amount: number, currency = 'INR') { return new Intl.NumberFormat(currency === 'INR' ? 'en-IN' : 'en-US',{style:'currency',currency,maximumFractionDigits:0}).format(amount * ({INR:1,USD:0.012,EUR:0.011,GBP:0.009}[currency as 'INR'] ?? 1)); }
export const totals = (items: Transaction[]) => ({ income: items.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0), expense:items.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0) });
export function formatDate(date: string, format: string) { const [y,m,d]=date.split('-'); return format==='YYYY-MM-DD' ? date : format==='MM/DD/YYYY' ? `${m}/${d}/${y}` : `${d}/${m}/${y}`; }
export function brainReply(question: string, items: Transaction[], goal: number) {
  const {income,expense}=totals(items); const byCategory=categories.map(category=>({category,total:items.filter(x=>x.category===category && x.type==='expense').reduce((a,x)=>a+x.amount,0)})).sort((a,b)=>b.total-a.total);
  const lead=byCategory[0]; const available=income-expense; const lower=question.toLowerCase();
  if (lower.includes('phone') || lower.includes('afford')) return `You have ${money(available)} left after recorded expenses. A new phone may fit your cash flow, but I’d keep at least one month of essential spending aside and protect your laptop fund (${money(goal)} saved so far). Consider setting a spending limit before buying.`;
  if (lower.includes('cut') || lower.includes('reduce')) return `Start with ${lead.category.toLowerCase()}, your largest spending category at ${money(lead.total)}. A 15% reduction there would free up about ${money(lead.total*.15)}. Review recurring purchases before cutting essentials.`;
  if (lower.includes('save')) return `Your current net cash flow is ${money(available)}. Putting aside 20% of that—${money(available*.2)}—would bring your laptop fund to ${money(goal+available*.2)}. Keep a separate emergency buffer too.`;
  if (lower.includes('most') || lower.includes('where')) return `Your largest category is ${lead.category} at ${money(lead.total)}, followed by ${byCategory[1].category.toLowerCase()} at ${money(byCategory[1].total)}. This is based on the transactions currently in your pocket.`;
  return `You’ve recorded ${money(income)} in income and ${money(expense)} in expenses. That’s ${income ? Math.round(expense/income*100) : 0}% of income spent, leaving ${money(available)}. ${lead.category} is your largest spending category at ${money(lead.total)}. You’re making good progress toward your laptop fund.`;
}
