import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { defaultPreferences, type Preferences, type Transaction, type Thread } from '@/lib/finance';
import type { Json } from '@/integrations/supabase/types';
import { toast } from 'sonner';
type Account = { id:string; name:string; email:string };
type Store = { ready:boolean; account:Account|null; transactions:Transaction[]; preferences:Preferences; goal:number; threads:Thread[]; signIn:(email:string,password:string)=>Promise<void>; signUp:(name:string,email:string,password:string)=>Promise<boolean>; signOut:()=>Promise<void>; signInGoogle:()=>Promise<void>; saveTransaction:(item:Transaction)=>Promise<void>; deleteTransaction:(id:string)=>Promise<void>; setPreferences:(value:Preferences)=>void; setGoal:(value:number)=>void; createThread:()=>string; saveThread:(thread:Thread)=>void; deleteThread:(id:string)=>void };
const Ctx=createContext<Store|null>(null);
const threadKey=(id:string)=>`ps-threads-${id}`;
function loadThreads(id:string):Thread[]{try{return JSON.parse(localStorage.getItem(threadKey(id))||'[]')}catch{return []}}
export function PocketProvider({children}:{children:ReactNode}) {
  const [ready,setReady]=useState(false); const [account,setAccount]=useState<Account|null>(null); const [transactions,setTransactions]=useState<Transaction[]>([]); const [preferences,setPreferencesState]=useState<Preferences>(defaultPreferences); const [goal,setGoalState]=useState(0); const [threads,setThreads]=useState<Thread[]>([]);const threadsRef=useRef<Thread[]>([]);
  useEffect(()=>{let active=true;let generation=0;const hydrate=async()=>{const current=++generation;const {data:{user}}=await supabase.auth.getUser();if(!active||current!==generation)return;if(!user){setAccount(null);setTransactions([]);setThreads([]);threadsRef.current=[];setPreferencesState(defaultPreferences);setGoalState(0);setReady(true);return}const [{data:profile},{data:rows,error:rowsError},{data:settings}]=await Promise.all([supabase.from('profiles').select('display_name').eq('id',user.id).maybeSingle(),supabase.from('finance_transactions').select('*').eq('user_id',user.id).order('transaction_date',{ascending:false}).limit(1000),supabase.from('pocket_settings').select('preferences,goal_saved').eq('user_id',user.id).maybeSingle()]);if(!active||current!==generation)return;if(rowsError)toast.error('Could not load your transactions');const name=profile?.display_name||user.user_metadata?.['name']||user.email?.split('@')[0]||'Friend';setAccount({id:user.id,email:user.email??'',name});if(!profile&&user.user_metadata?.['name'])void supabase.from('profiles').upsert({id:user.id,display_name:String(user.user_metadata['name'])});setTransactions((rows??[]).map(x=>({id:x.id,title:x.title,category:x.category,amount:Number(x.amount),type:x.type as Transaction['type'],date:x.transaction_date,method:x.payment_method})));setPreferencesState({...defaultPreferences,...(settings?.preferences as Partial<Preferences>??{})});setGoalState(Number(settings?.goal_saved??0));const stored=loadThreads(user.id);threadsRef.current=stored;setThreads(stored);setReady(true)};void hydrate();const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT'||event==='USER_UPDATED')void hydrate()});return()=>{active=false;subscription.unsubscribe()}},[]);
  const updateThreads=(next:Thread[])=>{threadsRef.current=next;setThreads(next);if(account)localStorage.setItem(threadKey(account.id),JSON.stringify(next))};
 const signIn=async(email:string,password:string)=>{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error};
  const signUp=async(name:string,email:string,password:string)=>{const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()}}});if(error)throw error;return Boolean(data.session)};
 const signInGoogle=async()=>{const {lovable}=await import('@/integrations/lovable');const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin+'/auth'});if(result.error)throw result.error};
 const signOut=async()=>{const {error}=await supabase.auth.signOut();if(error)throw error;setAccount(null);setTransactions([]);setThreads([])};
 const saveTransaction=async(item:Transaction)=>{if(!account)throw new Error('Sign in to save a transaction');const row={user_id:account.id,title:item.title,category:item.category,amount:item.amount,type:item.type,transaction_date:item.date,payment_method:item.method};const existing=transactions.some(x=>x.id===item.id);const result=existing?await supabase.from('finance_transactions').update(row).eq('id',item.id).eq('user_id',account.id).select().single():await supabase.from('finance_transactions').insert(row).select().single();if(result.error)throw result.error;const saved=result.data;setTransactions(current=>[{...item,id:saved.id},...current.filter(x=>x.id!==item.id)])};
 const deleteTransaction=async(id:string)=>{if(!account)throw new Error('Sign in first');const {error}=await supabase.from('finance_transactions').delete().eq('id',id).eq('user_id',account.id);if(error)throw error;setTransactions(current=>current.filter(x=>x.id!==id))};
 const persistSettings=async(value:Preferences,saved:number)=>{if(!account)return;const {error}=await supabase.from('pocket_settings').upsert({user_id:account.id,preferences:value as unknown as Json,goal_saved:saved});if(error)toast.error('Could not save your settings')};
  return <Ctx.Provider value={{ready,account,transactions,preferences,goal,threads,signIn,signUp,signOut,signInGoogle,saveTransaction,deleteTransaction,setPreferences:(value)=>{setPreferencesState(value);void persistSettings(value,goal)},setGoal:(value)=>{setGoalState(value);void persistSettings(preferences,value)},createThread:()=>{const id=crypto.randomUUID();updateThreads([{id,title:'New conversation',updatedAt:Date.now(),messages:[]},...threadsRef.current]);return id},saveThread:(thread)=>updateThreads([thread,...threadsRef.current.filter(x=>x.id!==thread.id)]),deleteThread:(id)=>updateThreads(threadsRef.current.filter(x=>x.id!==id))}}>{children}</Ctx.Provider>
}
export function usePocket(){const context=useContext(Ctx);if(!context)throw new Error('PocketProvider missing');return context}
