import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import { defaultPreferences, seedTransactions, type Preferences, type Transaction, type Thread } from '@/lib/finance';
type Account = { name: string; email: string; password: string };
type Store = { ready:boolean; account:Account|null; transactions:Transaction[]; preferences:Preferences; goal:number; threads:Thread[]; signIn:(email:string,password:string)=>boolean; signUp:(name:string,email:string,password:string)=>boolean; signOut:()=>void; saveTransaction:(item:Transaction)=>void; deleteTransaction:(id:string)=>void; setPreferences:(value:Preferences)=>void; setGoal:(value:number)=>void; createThread:()=>string; saveThread:(thread:Thread)=>void; deleteThread:(id:string)=>void };
const Ctx=createContext<Store|null>(null);
const read=<T,>(key:string,fallback:T):T=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}};
export function PocketProvider({children}:{children:ReactNode}) {
 const [ready,setReady]=useState(false); const [account,setAccount]=useState<Account|null>(null); const [transactions,setTransactions]=useState<Transaction[]>(seedTransactions); const [preferences,setPreferencesState]=useState<Preferences>(defaultPreferences); const [goal,setGoalState]=useState(32000); const [threads,setThreads]=useState<Thread[]>([]);
 useEffect(()=>{setAccount(read('ps-session',null));setTransactions(read('ps-transactions',seedTransactions));setPreferencesState(read('ps-preferences',defaultPreferences));setGoalState(read('ps-goal',32000));setThreads(read('ps-threads',[]));setReady(true)},[]);
 const updateTransactions=(next:Transaction[])=>{setTransactions(next);localStorage.setItem('ps-transactions',JSON.stringify(next))};
 const updateThreads=(next:Thread[])=>{setThreads(next);localStorage.setItem('ps-threads',JSON.stringify(next))};
 const signIn=(email:string,password:string)=>{const accounts=read<Account[]>('ps-accounts',[]);const found=accounts.find(x=>x.email===email.trim().toLowerCase()&&x.password===password);if(!found)return false;setAccount(found);localStorage.setItem('ps-session',JSON.stringify(found));return true};
 const signUp=(name:string,email:string,password:string)=>{const accounts=read<Account[]>('ps-accounts',[]);if(accounts.some(x=>x.email===email.trim().toLowerCase()))return false;const next={name:name.trim(),email:email.trim().toLowerCase(),password};localStorage.setItem('ps-accounts',JSON.stringify([...accounts,next]));setAccount(next);localStorage.setItem('ps-session',JSON.stringify(next));return true};
 return <Ctx.Provider value={{ready,account,transactions,preferences,goal,threads,signIn,signUp,signOut:()=>{setAccount(null);localStorage.removeItem('ps-session')},saveTransaction:(item)=>updateTransactions([item,...transactions.filter(x=>x.id!==item.id)]),deleteTransaction:(id)=>updateTransactions(transactions.filter(x=>x.id!==id)),setPreferences:(value)=>{setPreferencesState(value);localStorage.setItem('ps-preferences',JSON.stringify(value))},setGoal:(value)=>{setGoalState(value);localStorage.setItem('ps-goal',JSON.stringify(value))},createThread:()=>{const id=crypto.randomUUID();updateThreads([{id,title:'New conversation',updatedAt:Date.now(),messages:[]},...threads]);return id},saveThread:(thread)=>updateThreads([thread,...threads.filter(x=>x.id!==thread.id)]),deleteThread:(id)=>updateThreads(threads.filter(x=>x.id!==id))}}>{children}</Ctx.Provider>;
}
export function usePocket(){const context=useContext(Ctx);if(!context)throw new Error('PocketProvider missing');return context}
