import { useEffect, useState } from 'react';
import { z } from 'zod';
import { toast } from 'sonner';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { categories, type Transaction } from '@/lib/finance';
import { usePocket } from './store';
const schema=z.object({title:z.string().trim().min(2).max(80),amount:z.number().positive().max(10000000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),method:z.string().min(1),category:z.string().min(1)});
export function TransactionModal({open,onClose,type,editing}:{open:boolean;onClose:()=>void;type:'income'|'expense';editing?:Transaction|null}) {
 const {saveTransaction}=usePocket();const [title,setTitle]=useState('');const [amount,setAmount]=useState('');const [category,setCategory]=useState('Food');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [method,setMethod]=useState('UPI');const [error,setError]=useState('');
 useEffect(()=>{if(open){setTitle(editing?.title??'');setAmount(editing?.amount?.toString()??'');setCategory(editing?.category??(type==='income'?'Income':'Food'));setDate(editing?.date??new Date().toISOString().slice(0,10));setMethod(editing?.method??'UPI');setError('')}},[open,editing,type]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();const result=schema.safeParse({title,amount:Number(amount),category,date,method});if(!result.success){setError(result.error.issues[0]?.message??'Check your details');return}saveTransaction({id:editing?.id??crypto.randomUUID(),type,...result.data});toast.success(editing?'Transaction updated':'Transaction added');onClose()};
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-md rounded-2xl border-border bg-card"><DialogHeader><DialogTitle>{editing?'Edit':'Add'} {type==='income'?'income':'expense'}</DialogTitle><DialogDescription>Keep your money picture up to date.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4 pt-2"><label className="field-label">Amount<Input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0" required/></label><label className="field-label">{type==='income'?'Source':'Description'}<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='income'?'e.g. Freelance Project':'e.g. Coffee'} maxLength={80} required/></label><div className="grid grid-cols-2 gap-3"><label className="field-label">Category<select value={category} onChange={e=>setCategory(e.target.value)} className="field-select">{(type==='income'?['Income', 'Other']:categories).map(x=><option key={x}>{x}</option>)}</select></label><label className="field-label">Payment method<select value={method} onChange={e=>setMethod(e.target.value)} className="field-select">{['UPI','Debit card','Credit card','Bank transfer','Cash'].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="field-label">Date<Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="h-11 w-full" type="submit">{editing?'Save changes':'Add transaction'}</Button></form></DialogContent></Dialog>
}
