CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own profile" ON public.profiles FOR ALL TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.finance_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title text NOT NULL CHECK (char_length(title) BETWEEN 2 AND 80), category text NOT NULL, amount numeric(12,2) NOT NULL CHECK (amount > 0), type text NOT NULL CHECK (type IN ('income','expense')), transaction_date date NOT NULL, payment_method text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.finance_transactions TO authenticated;
GRANT ALL ON public.finance_transactions TO service_role;
ALTER TABLE public.finance_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own transactions" ON public.finance_transactions FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE INDEX finance_transactions_user_date_idx ON public.finance_transactions(user_id, transaction_date DESC);
CREATE TABLE public.pocket_settings (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, preferences jsonb NOT NULL DEFAULT '{}'::jsonb, goal_saved numeric(12,2) NOT NULL DEFAULT 0 CHECK (goal_saved >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pocket_settings TO authenticated;
GRANT ALL ON public.pocket_settings TO service_role;
ALTER TABLE public.pocket_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own settings" ON public.pocket_settings FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER touch_profiles BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_finance_transactions BEFORE UPDATE ON public.finance_transactions FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_pocket_settings BEFORE UPDATE ON public.pocket_settings FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();